                         -- SQLITE JOIN


CREATE TABLE A1(EM_ID INTEGER PRIMARY KEY NOT NULL,NAME TEXT NOT NULL,SALARY INTEGER NOT NULL);


CREATE TABLE B1(EM_ID INTEGER PRIMARY KEY NOT NULL,NAME TEXT NOT NULL,DEPARTMENT TEXT NOT NULL);


                         -- INNER JOIN

SELECT A1.EM_ID,NAME,B1.DEPARTMENT AS DEPARTMENT,SALARY FROM A1 INNER JOIN B1 ON A1.EM_ID=B1.EM_ID;

SELECT A1.EM_ID,NAME,B1.DEPARTMENT AS DEPARTMENT,SALARY FROM A1 INNER JOIN B1 ON A1.EM_ID=B1.EM_ID ORDER BY SALARY DESC;

SELECT A1.EM_ID,NAME,B1.DEPARTMENT AS DEPARTMENT,SALARY FROM A1 INNER JOIN B1 ON A1.EM_ID=B1.EM_ID WHERE DEPARTMENT='MOBILE';


                     -- LEFT JOIN
					 
	SELECT A1.EM_ID,NAME,B1.DEPARTMENT AS DEPARTMENT,SALARY FROM A1 LEFT JOIN B1 ON A1.EM_ID=B1.EM_ID;

	
	SELECT A1.EM_ID,NAME,B1.DEPARTMENT AS DEPARTMENT,SALARY FROM A1 LEFT JOIN B1 ON A1.EM_ID=B1.EM_ID WHERE DEPARTMENT IS NOT NULL;	
	

                    
			
	              		-- RIGHT and FULL OUTER JOINs are not currently supported(SQLITE)
						
						-- RIGHT JOIN BY SWITCHING POSITION OF TABLE

   SELECT A1.EM_ID,NAME,B1.DEPARTMENT AS DEPARTMENT,SALARY FROM B1 LEFT JOIN A1 ON A1.EM_ID=B1.EM_ID;
   
   
             -- FULL OUTER JOIN =RIGHT JOIN(RIGHT JOIN BY SWITCHING POSITION OF TABLE) UNION  LEFT JOIN
			 
			 
			SELECT A1.EM_ID,NAME,B1.DEPARTMENT AS DEPARTMENT,SALARY FROM A1 LEFT JOIN B1 ON A1.EM_ID=B1.EM_ID 
		    UNION
	        SELECT A1.EM_ID,NAME,B1.DEPARTMENT AS DEPARTMENT,SALARY FROM B1 LEFT JOIN A1 ON A1.EM_ID=B1.EM_ID;
			 
			 
						
						-- SELF JOIN 
						

    SELECT a.FirstName,b.ManagerID FROM Employees a JOIN Employees b 
		 ON b.EmployeeID=a.ManagerID;  
		
	 SELECT a.FirstName,b.FirstName FROM Employees a JOIN Employees b 
		 ON b.EmployeeID=a.ManagerID;  	

		 
		-- CROSS JOIN in SQlite
							
		
		 SELECT DEPARTMENT,SALARY FROM B1 CROSS JOIN A1;