           -- CREATE / ALTER /DROP SQLITE


		   
	CREATE TABLE XYZ(EM_ID INTEGER PRIMARY KEY,FIRSTNAME TEXT NOT NULL,SALARY INTEGER NOT NULL,BOB INTEGER NOT NULL);
	
	CREATE TABLE XYZ2(EM_ID INTEGER,FIRSTNAME TEXT NOT NULL,SALARY INTEGER NOT NULL,BOB INTEGER NOT NULL,PRIMARY KEY(EM_ID));
	
	CREATE TABLE XYZ3(EM_ID INTEGER ,FIRSTNAME TEXT NOT NULL,SALARY INTEGER NOT NULL,BOB INTEGER NOT NULL,FOREIGN KEY(EM_ID)REFERENCES XYZ2(EM_ID));
	
	
	CREATE TABLE A1(SR_NO INTEGER NOT NULL PRIMARY KEY , NAME TEXT NOT NULL,B_DATE TEXT CHECK( B_DATE like '____/__/__'));
	
	ALTER TABLE A1 ADD COLUMN CITY TEXT CHECK(CITY IN('TALOD','MODASA','AHM'));
	
	
	
	ALTER TABLE XYZ 
	ADD EMAIL TEXT NOT NULL;
	
	ALTER TABLE XYZ
	DROP COLUMN BOB;
	
	 ALTER TABLE A1 RENAME TO B1;             
			   
			   
			   
			   -- RENAME COLUMN NAME 
			   
			 ALTER TABLE B1 RENAME COLUMN 'NAME' TO 'FIRSTNAME';
			 
			 
			 
			 
			 
			 
	DROP TABLE XYZ;              
	
	DROP TABLE XYZ3;
	
	DROP TABLE XYZ2;      --  FOREIGN KEY CONSTRAINT FAILD;
	
